name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Build package
        run: bun build . --outfile index.js --no-bundle --minify

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  publish:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: List files
        run: tree -s -h

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
